default_install_types:
  python: true
  node: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-formatting]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy
        additional_dependencies: [pydantic]
        args: [--ignore-missing-imports]
        pass_filenames: false
        entry: uv run mypy

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.18.0
    hooks:
      - id: eslint
        args: [--fix]
        files: ^apps/frontend/.*

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.4.0
    hooks:
      - id: prettier
        args: [--write]
        files: ^apps/frontend/.*

  - repo: https://github.com/PyCQA/isort
    rev: 5.14.0
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: local
    hooks:
      - id: dbt-compile
        name: dbt-compile
        entry: uvx dbt-duckdb compile
        language: system
        pass_filenames: false
        always_run: true
        files: ^apps/analytics/.*
        stages: [push]

  - repo: https://github.com/shellcheck-py/shellcheck-pre-commit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        additional_dependencies: ['shellcheck-py']
