/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/attestations/content': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Attestation */
    post: operations['create_attestation_api_v1_attestations_content_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/attestations/{attestation_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Attestation */
    get: operations['get_attestation_api_v1_attestations__attestation_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/attestations/{attestation_id}/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verify Attestation */
    get: operations['verify_attestation_api_v1_attestations__attestation_id__verify_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/google/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Google Login */
    get: operations['google_login_api_v1_auth_google_login_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/google/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Google Callback */
    get: operations['google_callback_api_v1_auth_google_callback_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations['get_me_api_v1_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cards': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List My Cards */
    get: operations['list_my_cards_api_v1_cards_get'];
    put?: never;
    /** Create Card */
    post: operations['create_card_api_v1_cards_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cards/{card_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Card */
    get: operations['get_card_api_v1_cards__card_id__get'];
    put?: never;
    post?: never;
    /** Delete Card */
    delete: operations['delete_card_api_v1_cards__card_id__delete'];
    options?: never;
    head?: never;
    /** Update Card */
    patch: operations['update_card_api_v1_cards__card_id__patch'];
    trace?: never;
  };
  '/api/v1/cards/{card_id}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish Card */
    post: operations['publish_card_api_v1_cards__card_id__publish_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/@{creator_slug}/{card_slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Public Card */
    get: operations['get_public_card_api_v1___creator_slug___card_slug__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cards/{card_id}/claim-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Claim Request */
    post: operations['create_claim_request_api_v1_cards__card_id__claim_requests_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/og': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Og Image */
    get: operations['og_image_api_v1_og_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sources/extract': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Extract Url Metadata
     * @description Extract title, authors, date, citations from a URL (best-effort, no auth required).
     *
     *     Protected against SSRF: the URL is resolved and any non-public IP
     *     (loopback, private RFC1918, link-local, cloud-metadata 169.254.169.254,
     *     etc.) is rejected up-front. See `app.core.url_safety`.
     */
    get: operations['extract_url_metadata_api_v1_sources_extract_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sources */
    get: operations['list_sources_api_v1_sources_get'];
    put?: never;
    /** Create Source */
    post: operations['create_source_api_v1_sources_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sources/{source_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Source */
    delete: operations['delete_source_api_v1_sources__source_id__delete'];
    options?: never;
    head?: never;
    /** Update Source */
    patch: operations['update_source_api_v1_sources__source_id__patch'];
    trace?: never;
  };
  '/api/v1/users/@{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Profile */
    get: operations['get_user_profile_api_v1_users___slug__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/waitlist': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join Waitlist */
    post: operations['join_waitlist_api_v1_waitlist_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations['health_check_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/database': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Database Health */
    get: operations['database_health_health_database_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/publish-diagnose': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Publish Diagnose
     * @description Exercise the publish code path on the demo user's seeded card.
     *
     *     Debug-only: returns tracebacks and internal paths, so it must not be
     *     reachable on a production deployment (debug=false). Dry-run: the UPDATE
     *     is flushed (exercising the exact DB write path) then rolled back.
     */
    get: operations['publish_diagnose_health_publish_diagnose_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/seed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Seed Health
     * @description Diagnose: does the demo user + card exist? Debug-only.
     *
     *     Enumerates every username and card slug, so it must not be reachable
     *     on a production deployment (debug=false).
     */
    get: operations['seed_health_health_seed_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ArchiveStatus
     * @enum {string}
     */
    ArchiveStatus: 'pending' | 'archived' | 'failed';
    /** AttestationCreate */
    AttestationCreate: {
      /** Content Url */
      content_url: string;
    };
    /** AttestationResponse */
    AttestationResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Content Url */
      content_url: string;
      /**
       * Attested At
       * Format: date-time
       */
      attested_at: string;
      /** Canonical Hash */
      canonical_hash: string;
      /** Signature */
      signature: string;
      /** Created At */
      created_at: string | null;
    };
    /** AttestationVerifyResponse */
    AttestationVerifyResponse: {
      /** Valid */
      valid: boolean;
      /** Attestation Id */
      attestation_id?: string | null;
      /** Content Url */
      content_url?: string | null;
      /** Creator Slug */
      creator_slug?: string | null;
      /** Public Key */
      public_key?: string | null;
      /**
       * Hash Algorithm
       * @default SHA-256
       */
      hash_algorithm: string;
      /**
       * Signature Algorithm
       * @default Ed25519
       */
      signature_algorithm: string;
      /**
       * Canonicalization
       * @default RFC 8785 JSON Canonicalization Scheme
       */
      canonicalization: string;
      /** Reason */
      reason?: string | null;
    };
    /**
     * AuthorKind
     * @enum {string}
     */
    AuthorKind:
      | 'chercheur'
      | 'media'
      | 'institution-publique'
      | 'gouvernement'
      | 'ecole'
      | 'laboratoire'
      | 'entreprise'
      | 'asso'
      | 'individu';
    /** CardCreate */
    CardCreate: {
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** Content Url */
      content_url?: string | null;
      /** @default other */
      platform: components['schemas']['Platform'];
      /** @default video */
      content_type: components['schemas']['ContentType'];
    };
    /** CardDetail */
    CardDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /** Content Url */
      content_url: string | null;
      platform: components['schemas']['Platform'];
      content_type: components['schemas']['ContentType'];
      status: components['schemas']['CardStatus'];
      /**
       * Is Seed
       * @default false
       */
      is_seed: boolean;
      /** Published At */
      published_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at: string | null;
      creator: components['schemas']['CreatorInfo'];
      /** Sources */
      sources: components['schemas']['SourceResponse'][];
      stats: components['schemas']['CardStats'];
    };
    /** CardResponse */
    CardResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /** Content Url */
      content_url: string | null;
      platform: components['schemas']['Platform'];
      content_type: components['schemas']['ContentType'];
      status: components['schemas']['CardStatus'];
      /**
       * Is Seed
       * @default false
       */
      is_seed: boolean;
      /** Published At */
      published_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at: string | null;
    };
    /** CardStats */
    CardStats: {
      /**
       * Total Sources
       * @default 0
       */
      total_sources: number;
      /**
       * Chercheur
       * @default 0
       */
      chercheur: number;
      /**
       * Media
       * @default 0
       */
      media: number;
      /**
       * Institution Publique
       * @default 0
       */
      institution_publique: number;
      /**
       * Individu
       * @default 0
       */
      individu: number;
      /**
       * Archived Count
       * @default 0
       */
      archived_count: number;
      /**
       * All Archived
       * @default false
       */
      all_archived: boolean;
    };
    /**
     * CardStatus
     * @enum {string}
     */
    CardStatus: 'draft' | 'published' | 'archived';
    /** CardUpdate */
    CardUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Content Url */
      content_url?: string | null;
      platform?: components['schemas']['Platform'] | null;
    };
    /** ClaimRequestCreate */
    ClaimRequestCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Channel Url */
      channel_url: string;
      /** Message */
      message?: string | null;
    };
    /** ClaimRequestResponse */
    ClaimRequestResponse: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /**
     * ContentType
     * @enum {string}
     */
    ContentType: 'video' | 'article' | 'post' | 'podcast' | 'other';
    /** CreatorInfo */
    CreatorInfo: {
      /** Slug */
      slug: string;
      /** Display Name */
      display_name: string | null;
      /** Bio */
      bio: string | null;
      /** Avatar Url */
      avatar_url: string | null;
      /** Public Key */
      public_key: string;
    };
    /** ExtractResponse */
    ExtractResponse: {
      /** Title */
      title: string | null;
      /** Authors */
      authors: string | null;
      /** Published At */
      published_at: string | null;
      /** Description */
      description: string | null;
      /** Citations Count */
      citations_count: number | null;
      /** Impact Factor */
      impact_factor: number | null;
      /** Format */
      format?: string | null;
      /** Category */
      category?: string | null;
      /** Author Kind */
      author_kind?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * Platform
     * @enum {string}
     */
    Platform: 'youtube' | 'podcast' | 'blog' | 'x' | 'bluesky' | 'other';
    /**
     * SourceCategory
     * @enum {string}
     */
    SourceCategory:
      | 'article-scientifique'
      | 'preprint'
      | 'article-presse'
      | 'communique'
      | 'documentaire'
      | 'interview'
      | 'podcast'
      | 'blog'
      | 'post-social'
      | 'livre'
      | 'page-web'
      | 'notes';
    /** SourceCreate */
    SourceCreate: {
      /** Url */
      url: string;
      /** Title */
      title?: string | null;
      /** Authors */
      authors?: string | null;
      /** Published At */
      published_at?: string | null;
      format: components['schemas']['SourceFormat'];
      category: components['schemas']['SourceCategory'];
      author_kind: components['schemas']['AuthorKind'];
      /** Annotation */
      annotation?: string | null;
      /**
       * Is Pivot
       * @default false
       */
      is_pivot: boolean;
      /** Parent Source Id */
      parent_source_id?: string | null;
      /** Archive Url */
      archive_url?: string | null;
    };
    /** SourceExcerptResponse */
    SourceExcerptResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Position */
      position: number;
      /** Text */
      text: string;
      /** Suggested By Ai */
      suggested_by_ai: boolean;
    };
    /**
     * SourceFormat
     * @enum {string}
     */
    SourceFormat: 'texte' | 'video' | 'image' | 'audio' | 'data';
    /** SourceResponse */
    SourceResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Url */
      url: string;
      /** Title */
      title: string | null;
      /** Authors */
      authors: string | null;
      /** Published At */
      published_at: string | null;
      format: components['schemas']['SourceFormat'];
      category: components['schemas']['SourceCategory'];
      author_kind: components['schemas']['AuthorKind'];
      /** Annotation */
      annotation: string | null;
      /** Is Pivot */
      is_pivot: boolean;
      archive_status: components['schemas']['ArchiveStatus'];
      /** Archive Url */
      archive_url: string | null;
      /** Archive Timestamp */
      archive_timestamp: string | null;
      /** Parent Source Id */
      parent_source_id: string | null;
      /** Conflict Of Interest */
      conflict_of_interest?: string | null;
      /** Citations Count */
      citations_count?: number | null;
      /** Subscribers Count */
      subscribers_count?: number | null;
      /** Views Count */
      views_count?: number | null;
      /** Impact Factor */
      impact_factor?: number | null;
      /** Excerpts */
      excerpts?: components['schemas']['SourceExcerptResponse'][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at: string | null;
    };
    /** SourceUpdate */
    SourceUpdate: {
      /** Title */
      title?: string | null;
      /** Authors */
      authors?: string | null;
      /** Published At */
      published_at?: string | null;
      format?: components['schemas']['SourceFormat'] | null;
      category?: components['schemas']['SourceCategory'] | null;
      author_kind?: components['schemas']['AuthorKind'] | null;
      /** Annotation */
      annotation?: string | null;
      /** Is Pivot */
      is_pivot?: boolean | null;
      /** Parent Source Id */
      parent_source_id?: string | null;
      /** Archive Url */
      archive_url?: string | null;
    };
    /** UserResponse */
    UserResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Username */
      username: string;
      /** Display Name */
      display_name: string | null;
      /** Bio */
      bio: string | null;
      /** Avatar Url */
      avatar_url: string | null;
      /** Is Verified */
      is_verified: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WaitlistCreate */
    WaitlistCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Context
       * @default home
       */
      context: string;
    };
    /** WaitlistResponse */
    WaitlistResponse: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  create_attestation_api_v1_attestations_content_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AttestationCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AttestationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_attestation_api_v1_attestations__attestation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attestation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AttestationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  verify_attestation_api_v1_attestations__attestation_id__verify_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attestation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AttestationVerifyResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  google_login_api_v1_auth_google_login_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  google_callback_api_v1_auth_google_callback_get: {
    parameters: {
      query?: {
        code?: string | null;
        state?: string | null;
        error?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
    };
  };
  list_my_cards_api_v1_cards_get: {
    parameters: {
      query?: {
        status?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CardResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_card_api_v1_cards_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CardCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CardResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_card_api_v1_cards__card_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        card_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CardResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_card_api_v1_cards__card_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        card_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_card_api_v1_cards__card_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        card_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CardUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CardResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  publish_card_api_v1_cards__card_id__publish_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        card_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_public_card_api_v1___creator_slug___card_slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        creator_slug: string;
        card_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CardDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_claim_request_api_v1_cards__card_id__claim_requests_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        card_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ClaimRequestCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClaimRequestResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  og_image_api_v1_og_get: {
    parameters: {
      query: {
        /** @description Card title to show in the image */
        title: string;
        /** @description Creator name */
        creator?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  extract_url_metadata_api_v1_sources_extract_get: {
    parameters: {
      query: {
        /** @description URL to extract metadata from */
        url: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExtractResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_sources_api_v1_sources_get: {
    parameters: {
      query: {
        /** @description Card ID to list sources for */
        card_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_source_api_v1_sources_post: {
    parameters: {
      query: {
        card_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SourceCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_source_api_v1_sources__source_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_source_api_v1_sources__source_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SourceUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SourceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_profile_api_v1_users___slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  join_waitlist_api_v1_waitlist_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WaitlistCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WaitlistResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  database_health_health_database_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  publish_diagnose_health_publish_diagnose_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  seed_health_health_seed_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
